function [ options ] = gen_training_options( learn_rate, max_epoch, batch_size )
%gen_training_options define the optimizer for training
% Input:
%	learn_rate:
%	max_epoch:
%	batch_size:
% Output:
%	options:	


options = trainingOptions('adam',...
    'LearnRateSchedule','none',...
    'InitialLearnRate', learn_rate,...
    'MaxEpochs',max_epoch,...
    'MiniBatchSize',batch_size, ...
    'LearnRateDropFactor', 0.1, ...
    'GradientDecayFactor', 0.9, ...
    'SquaredGradientDecayFactor', 0.85, ...
    'L2Regularization', 0.5, ...
    'VerboseFrequency', 1);
    %'CheckpointPath', '.\\data\\demo'


end
